### ISSUE TITLE
Run program with arguments

### ISSUE THREAD

**Issue by raphaelDkhn** [reilabs/cairo-hints#22]
Currently, only functions without arguments can be executed with `scarb-hints-run`, it would be great to add the `--args` flag similar to what is done with [CairoVM](https://github.com/lambdaclass/cairo-vm/blob/main/cairo1-run/README.md#cli-argument-list).

**Comment by gswirski** [comment]
Hi @raphaelDkhn, I like the idea!

Implementing it shouldn't be very difficult. `scarb-hints-run` is already based on the `cairo1-run` script that you linked to. Adding this option would require adding `--args` parameter to the clap parser and propagating it all the way to the VM.

It you need it, we would be happy to accept it as a contribution.
